version: '3'

services:
    app:
      container_name: app
      restart: always
      build: .
      ports:
        - '3000:3000'
      links:
        - mongo
      volumes:
        - .:/usr/src/app
    mongo:
        image: mongo
        container_name: mongoDB
        restart: always
        ports:
            - '27018:27017'
        volumes:
            - ./data:/data/db
        logging: 
          driver: none
    

